OLLAMA_CLIENT = "http://192.168.0.1:1881/"
PERSISTENT_DIR = "./user_data/threads/threads.db"
UPLOAD_DIR = "./user_data/temp"
OUTPUT_DIR = "./user_data/outputs"
VECTORSTORE_DIR = "./user_data/vectorstore/"
