# .streamlit/config.toml
[global]
developmentMode = false

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
layout="wide"
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#512967"    
        
#backgroundColor = "#f5f5f5"          
#secondaryBackgroundColor = "#e3ddef" 
textColor = "#1f1f1f"                
font = "sans serif"

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[theme.sidebar]
# Primary accent color.
primaryColor = "#512967"
#backgroundColor = "#E8E8E8" 

# Background color of the app.
# backgroundColor =

# Background color used for most interactive widgets.
#secondaryBackgroundColor = "#e3ddef"