# .streamlit/config.toml
[global]
developmentMode = false

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#984a9c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"
font = "sans serif"

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[theme.sidebar]
# Primary accent color.
primaryColor = "#984a9c"

# Background color of the app.
# backgroundColor =

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#fbdefc"